### ISSUE TITLE
domain bsp.

### ISSUE THREAD

**Issue by efor89** [xXMcpeGamerXx03/AntiWerbung#1]
hi
kurze frage wie add ich eine domain genau muss ich denn vollständigen namen angeben test.de oder reicht .de?

mfg efor89

**Comment by xXMcpeGamerXx03** [comment]
Wenn du die Domain .de Blockieren willst musst du ganz einfach "/antiwerbung add .de" eingeben, wenn du dann z.B. test.de eingibst wird die Nachricht nicht gesendet. Wenn du aber die Permission "antiwerbung.bypass" hast wird die Message gesendet.
Und wenn du die Domain wieder entfernen willst machst du einfach "/antiwerbung remove .de" und wenn du dann z.B. wieder test.de eingibst wird die Nachricht gesendet.
Um eine liste aller hinzugefügten Domains zu erhalten musst du "/antiwerbung list" eingeben.
Ich hoffe ich konnte dir weiter helfen. ^^

**Comment by efor89** [comment]
perfekt danke dir

**Comment by efor89** [comment]
geht auch dc blocken?

**Comment by efor89** [comment]
könntest du das hinzufügen das wäre noch sehr hilfreich mit einer bypass config so das man seinen eigenen dc link noch posten kann?

**Comment by supercrafter333** [comment]
Die Plugin ist schon bisschen umständlich gecodet xD. 
Ich denke er wird das machen :)

**Comment by supercrafter333** [comment]
Ich denke er wird es bald machen.

**Comment by xXMcpeGamerXx03** [comment]
Könnte in einem Update kommen! :-)

**Comment by xXMcpeGamerXx03** [comment]
haha :->
